ITEM_TYPE_DATA = {
    "Abyssal Axe": "weapon2h",
    "Abyssal Sceptre": "weapon1h",
    "Agate Amulet": "amulet",
    "Alder Spike Shield": "shield",
    "Alloyed Spike Shield": "shield",
    "Amber Amulet": "amulet",
    "Ambush Boots": "feet",
    "Ambush Mitts": "hands",
    "Ambusher": "weapon1h",
    "Amethyst Ring": "ring",
    "Ancestral Club": "weapon1h",
    "Ancient Gauntlets": "hands",
    "Ancient Greaves": "feet",
    "Ancient Spirit Shield": "shield",
    "Ancient Sword": "weapon1h",
    "Angelic Kite Shield": "shield",
    "Antique Gauntlets": "hands",
    "Antique Greaves": "feet",
    "Antique Rapier": "weapon1h",
    "Apex Rapier": "weapon1h",
    "Arachnid Nest Map": "map",
    "Arcanist Gloves": "hands",
    "Arcanist Slippers": "feet",
    "Archon Kite Shield": "shield",
    "Arena Plate": "chest",
    "Arming Axe": "weapon1h",
    "Assassin's Boots": "feet",
    "Assassin's Garb": "chest",
    "Assassin's Mitts": "hands",
    "Astral Plate": "chest",
    "Auric Mace": "weapon1h",
    "Aventail Helmet": "head",
    "Awl": "weapon1h",
    "Barbed Club": "weapon1h",
    "Barbute Helmet": "head",
    "Baroque Round Shield": "shield",
    "Baselard": "weapon1h",
    "Basket Rapier": "weapon1h",
    "Bastard Sword": "weapon2h",
    "Battered Foil": "weapon1h",
    "Battered Helm": "head",
    "Battle Buckler": "shield",
    "Battle Hammer": "weapon1h",
    "Battle Lamellar": "chest",
    "Battle Plate": "chest",
    "Battle Sword": "weapon1h",
    "Bladed Mace": "weapon1h",
    "Blinder": "weapon1h",
    "Blood Raiment": "chest",
    "Blood Sceptre": "weapon1h",
    "Boarding Axe": "weapon1h",
    "Bog Map": "map",
    "Bone Armour": "chest",
    "Bone Bow": "weapon2h",
    "Bone Circlet": "head",
    "Bone Spirit Shield": "shield",
    "Boot Blade": "weapon1h",
    "Boot Knife": "weapon1h",
    "Branded Kite Shield": "shield",
    "Brass Maul": "weapon2h",
    "Brass Spirit Shield": "shield",
    "Broad Axe": "weapon1h",
    "Broad Sword": "weapon1h",
    "Bronze Gauntlets": "hands",
    "Bronze Plate": "chest",
    "Bronze Sceptre": "weapon1h",
    "Bronze Tower Shield": "shield",
    "Bronzescale Boots": "feet",
    "Bronzescale Gauntlets": "hands",
    "Buckskin Tower Shield": "shield",
    "Buckskin Tunic": "chest",
    "Burnished Foil": "weapon1h",
    "Burnished Spike Shield": "shield",
    "Butcher Axe": "weapon1h",
    "Butcher Knife": "weapon1h",
    "Butcher Sword": "weapon2h",
    "Cabalist Regalia": "chest",
    "Callous Mask": "head",
    "Canyon Map": "map",
    "Cardinal Round Shield": "shield",
    "Carnal Armour": "chest",
    "Carnal Boots": "feet",
    "Carnal Mitts": "hands",
    "Carnal Sceptre": "weapon1h",
    "Carved Wand": "weapon1h",
    "Carving Knife": "weapon1h",
    "Cat's Paw": "weapon1h",
    "Catacomb Map": "map",
    "Cedar Tower Shield": "shield",
    "Cells Map": "map",
    "Cemetery Map": "map",
    "Ceremonial Axe": "weapon1h",
    "Ceremonial Kite Shield": "shield",
    "Ceremonial Mace": "weapon1h",
    "Chain Belt": "belt",
    "Chain Boots": "feet",
    "Chain Gloves": "hands",
    "Chain Hauberk": "chest",
    "Chainmail Doublet": "chest",
    "Chainmail Tunic": "chest",
    "Chainmail Vest": "chest",
    "Champion Kite Shield": "shield",
    "Chest Splitter": "weapon1h",
    "Chestplate": "chest",
    "Chiming Spirit Shield": "shield",
    "Citadel Bow": "weapon2h",
    "Citrine Amulet": "amulet",
    "Clasped Boots": "feet",
    "Clasped Mitts": "hands",
    "Cleaver": "weapon1h",
    "Close Helmet": "head",
    "Cloth Belt": "belt",
    "Coiled Staff": "weapon2h",
    "Colossal Tower Shield": "shield",
    "Colosseum Plate": "chest",
    "Colossus Mallet": "weapon2h",
    "Commander's Brigandine": "chest",
    "Composite Bow": "weapon2h",
    "Compound Bow": "weapon2h",
    "Compound Spiked Shield": "shield",
    "Conductive Quiver": "quiver",
    "Cone Helmet": "head",
    "Conjurer Boots": "feet",
    "Conjurer Gloves": "hands",
    "Conjurer's Vestment": "chest",
    "Conquest Chainmail": "chest",
    "Copper Kris": "weapon1h",
    "Copper Plate": "chest",
    "Copper Sword": "weapon1h",
    "Copper Tower Shield": "shield",
    "Coral Amulet": "amulet",
    "Coral Ring": "ring",
    "Coronal Leather": "chest",
    "Corroded Blade": "weapon2h",
    "Corroded Tower Shield": "shield",
    "Corrugated Buckler": "shield",
    "Corsair Sword": "weapon1h",
    "Coves Map": "map",
    "Crematorium Map": "map",
    "Crested Tower Shield": "shield",
    "Crimson Raiment": "chest",
    "Crimson Round Shield": "shield",
    "Crude Bow": "weapon2h",
    "Crusader Boots": "feet",
    "Crusader Buckler": "shield",
    "Crusader Chainmail": "chest",
    "Crusader Gloves": "hands",
    "Crusader Helmet": "head",
    "Crusader Plate": "chest",
    "Crypt Armour": "chest",
    "Crypt Map": "map",
    "Crystal Sceptre": "weapon1h",
    "Crystal Wand": "weapon1h",
    "Cured Quiver": "quiver",
    "Cutlass": "weapon1h",
    "Cutthroat's Garb": "chest",
    "Dark Forest Map": "map",
    "Darkwood Sceptre": "weapon1h",
    "Death Bow": "weapon2h",
    "Decimation Bow": "weapon2h",
    "Decorative Axe": "weapon1h",
    "Decurve Bow": "weapon2h",
    "Deerskin Boots": "feet",
    "Deerskin Gloves": "hands",
    "Deicide Mask": "head",
    "Demon Dagger": "weapon1h",
    "Demon's Horn": "weapon1h",
    "Desert Brigandine": "chest",
    "Despot Axe": "weapon2h",
    "Destiny Leather": "chest",
    "Destroyer Regalia": "chest",
    "Devout Chainmail": "chest",
    "Diamond Ring": "ring",
    "Double Axe": "weapon2h",
    "Dragonbone Rapier": "weapon1h",
    "Dragonscale Boots": "feet",
    "Dragonscale Doublet": "chest",
    "Dragonscale Gauntlets": "hands",
    "Dread Maul": "weapon2h",
    "Dream Mace": "weapon1h",
    "Dried Lake Map": "map",
    "Driftwood Club": "weapon1h",
    "Driftwood Maul": "weapon2h",
    "Driftwood Sceptre": "weapon1h",
    "Driftwood Spiked Shield": "shield",
    "Driftwood Wand": "weapon1h",
    "Dry Peninsula Map": "map",
    "Dry Woods Map": "map",
    "Dunes Map": "map",
    "Dungeon Map": "map",
    "Dusk Blade": "weapon1h",
    "Eagle Claw": "weapon1h",
    "Ebony Tower Shield": "shield",
    "Eelskin Boots": "feet",
    "Eelskin Gloves": "hands",
    "Eelskin Tunic": "chest",
    "Elder Sword": "weapon1h",
    "Elegant Foil": "weapon1h",
    "Elegant Ringmail": "chest",
    "Elegant Round Shield": "shield",
    "Elegant Sword": "weapon1h",
    "Embroidered Gloves": "hands",
    "Enameled Buckler": "shield",
    "Engraved Greatsword": "weapon2h",
    "Engraved Wand": "weapon1h",
    "Estoc": "weapon1h",
    "Etched Greatsword": "weapon2h",
    "Etched Shield": "shield",
    "Eternal Burgonet": "head",
    "Eternal Sword": "weapon1h",
    "Exquisite Leather": "chest",
    "Eye Gouger": "weapon1h",
    "Ezomyte Axe": "weapon2h",
    "Ezomyte Blade": "weapon2h",
    "Ezomyte Burgonet": "head",
    "Ezomyte Dagger": "weapon1h",
    "Ezomyte Spiked Shield": "shield",
    "Ezomyte Staff": "weapon2h",
    "Ezomyte Tower Shield": "shield",
    "Fancy Foil": "weapon1h",
    "Faun's Horn": "weapon1h",
    "Fencer Helm": "head",
    "Festival Mask": "head",
    "Field Lamellar": "chest",
    "Fiend Dagger": "weapon1h",
    "Fir Round Shield": "shield",
    "Fishscale Gauntlets": "hands",
    "Flanged Mace": "weapon1h",
    "Flaying Knife": "weapon1h",
    "Fluted Bascinet": "head",
    "Footman Sword": "weapon2h",
    "Fossilized Spirit Shield": "shield",
    "Foul Staff": "weapon2h",
    "Fright Claw": "weapon1h",
    "Fright Maul": "weapon2h",
    "Frontier Leather": "chest",
    "Full Chainmail": "chest",
    "Full Dragonscale": "chest",
    "Full Leather": "chest",
    "Full Plate": "chest",
    "Full Ringmail": "chest",
    "Full Scale Armour": "chest",
    "Full Wyrmscale": "chest",
    "Gavel": "weapon1h",
    "Gemstone Sword": "weapon1h",
    "General's Brigandine": "chest",
    "Gilded Axe": "weapon2h",
    "Gilded Buckler": "shield",
    "Gilded Sallet": "head",
    "Girded Tower Shield": "shield",
    "Gladiator Helmet": "head",
    "Gladiator Plate": "chest",
    "Gladius": "weapon1h",
    "Glass Shank": "weapon1h",
    "Glorious Leather": "chest",
    "Glorious Plate": "chest",
    "Gnarled Branch": "weapon2h",
    "Goat's Horn": "weapon1h",
    "Goathide Boots": "feet",
    "Goathide Buckler": "shield",
    "Goathide Gloves": "hands",
    "Gold Amulet": "amulet",
    "Gold Ring": "ring",
    "Golden Buckler": "shield",
    "Golden Kris": "weapon1h",
    "Golden Mask": "head",
    "Golden Plate": "chest",
    "Goliath Gauntlets": "hands",
    "Goliath Greaves": "feet",
    "Gorge Map": "map",
    "Gouger": "weapon1h",
    "Graceful Sword": "weapon1h",
    "Graveyard Map": "map",
    "Great Crown": "head",
    "Great Helmet": "head",
    "Great Mallet": "weapon2h",
    "Great White Claw": "weapon1h",
    "Grinning Fetish": "weapon1h",
    "Grotto Map": "map",
    "Grove Bow": "weapon2h",
    "Gut Ripper": "weapon1h",
    "Gutting Knife": "weapon1h",
    "Hammered Buckler": "shield",
    "Harbinger Bow": "weapon2h",
    "Harlequin Mask": "head",
    "Harmonic Spirit Shield": "shield",
    "Harpy Rapier": "weapon1h",
    "Headman's Sword": "weapon2h",
    "Headsman Axe": "weapon2h",
    "Heavy Belt": "belt",
    "Heavy Quiver": "quiver",
    "Hellion's Paw": "weapon1h",
    "Highborn Bow": "weapon2h",
    "Highborn Staff": "weapon2h",
    "Highland Blade": "weapon2h",
    "Holy Chainmail": "chest",
    "Hubris Circlet": "head",
    "Hunter Hood": "head",
    "Hussar Brigandine": "chest",
    "Hydrascale Boots": "feet",
    "Hydrascale Gauntlets": "hands",
    "Imbued Wand": "weapon1h",
    "Imp Dagger": "weapon1h",
    "Imperial Bow": "weapon2h",
    "Imperial Buckler": "shield",
    "Imperial Claw": "weapon1h",
    "Imperial Maul": "weapon2h",
    "Imperial Skean": "weapon1h",
    "Imperial Staff": "weapon2h",
    "Infantry Brigandine": "chest",
    "Infernal Axe": "weapon1h",
    "Infernal Sword": "weapon2h",
    "Iron Circlet": "head",
    "Iron Gauntlets": "hands",
    "Iron Greaves": "feet",
    "Iron Hat": "head",
    "Iron Mask": "head",
    "Iron Ring": "ring",
    "Iron Sceptre": "weapon1h",
    "Iron Staff": "weapon2h",
    "Ironscale Boots": "feet",
    "Ironscale Gauntlets": "hands",
    "Ironwood Buckler": "shield",
    "Ivory Bow": "weapon2h",
    "Ivory Spirit Shield": "shield",
    "Jade Amulet": "amulet",
    "Jade Chopper": "weapon2h",
    "Jade Hatchet": "weapon1h",
    "Jagged Foil": "weapon1h",
    "Jasper Axe": "weapon1h",
    "Jasper Chopper": "weapon2h",
    "Jeweled Foil": "weapon1h",
    "Jingling Spirit Shield": "shield",
    "Judgement Staff": "weapon2h",
    "Jungle Valley Map": "map",
    "Karui Axe": "weapon1h",
    "Karui Chopper": "weapon2h",
    "Karui Maul": "weapon2h",
    "Karui Sceptre": "weapon1h",
    "Labrys": "weapon2h",
    "Lacewood Spirit Shield": "shield",
    "Lacquered Buckler": "shield",
    "Lacquered Garb": "chest",
    "Lacquered Helmet": "head",
    "Laminated Kite Shield": "shield",
    "Lapis Amulet": "amulet",
    "Lathi": "weapon2h",
    "Latticed Ringmail": "chest",
    "Layered Kite Shield": "shield",
    "Lead Sceptre": "weapon1h",
    "Leather Belt": "belt",
    "Leather Cap": "head",
    "Leather Hood": "head",
    "Leatherscale Boots": "feet",
    "Legion Boots": "feet",
    "Legion Gloves": "hands",
    "Legion Hammer": "weapon1h",
    "Legion Sword": "weapon1h",
    "Light Brigandine": "chest",
    "Light Quiver": "quiver",
    "Linden Kite Shield": "shield",
    "Lion Pelt": "head",
    "Lion Sword": "weapon2h",
    "Long Bow": "weapon2h",
    "Long Staff": "weapon2h",
    "Longsword": "weapon2h",
    "Lordly Plate": "chest",
    "Loricated Ringmail": "chest",
    "Lunaris Circlet": "head",
    "Maelstr\u00f6m Staff": "weapon2h",
    "Mage's Vestment": "chest",
    "Magistrate Crown": "head",
    "Mahogany Tower Shield": "shield",
    "Majestic Plate": "chest",
    "Mallet": "weapon2h",
    "Maple Round Shield": "shield",
    "Maraketh Bow": "weapon2h",
    "Marsh Map": "map",
    "Maze Map": "map",
    "Meatgrinder": "weapon2h",
    "Mesh Boots": "feet",
    "Mesh Gloves": "hands",
    "Midnight Blade": "weapon1h",
    "Military Staff": "weapon2h",
    "Mind Cage": "head",
    "Mine Map": "map",
    "Mirrored Spiked Shield": "shield",
    "Moonstone Ring": "ring",
    "Mosaic Kite Shield": "shield",
    "Mountain Ledge Map": "map",
    "Mud Geyser Map": "map",
    "Murder Boots": "feet",
    "Murder Mitts": "hands",
    "Nailed Fist": "weapon1h",
    "Necromancer Circlet": "head",
    "Necromancer Silks": "chest",
    "Necropolis Map": "map",
    "Nightmare Bascinet": "head",
    "Nightmare Mace": "weapon1h",
    "Noble Axe": "weapon2h",
    "Noble Claw": "weapon1h",
    "Noble Tricorne": "head",
    "Nubuck Boots": "feet",
    "Nubuck Gloves": "hands",
    "Oak Buckler": "shield",
    "Occultist's Vestment": "chest",
    "Ochre Sceptre": "weapon1h",
    "Oiled Coat": "chest",
    "Oiled Vest": "chest",
    "Omen Wand": "weapon1h",
    "Onyx Amulet": "amulet",
    "Opal Sceptre": "weapon1h",
    "Opal Wand": "weapon1h",
    "Ornate Mace": "weapon1h",
    "Ornate Ringmail": "chest",
    "Ornate Spiked Shield": "shield",
    "Ornate Sword": "weapon2h",
    "Overgrown Ruin Map": "map",
    "Overgrown Shrine Map": "map",
    "Padded Jacket": "chest",
    "Padded Vest": "chest",
    "Painted Buckler": "shield",
    "Painted Tower Shield": "shield",
    "Paua Amulet": "amulet",
    "Paua Ring": "ring",
    "Pecoraro": "weapon1h",
    "Pernarch": "weapon1h",
    "Petrified Club": "weapon1h",
    "Phantom Mace": "weapon1h",
    "Pig Faced Bascinet": "head",
    "Piledriver": "weapon2h",
    "Pine Buckler": "shield",
    "Pinnacle Tower Shield": "shield",
    "Plague Mask": "head",
    "Plank Kite Shield": "shield",
    "Plate Vest": "chest",
    "Plateau Map": "map",
    "Plated Gauntlets": "hands",
    "Plated Greaves": "feet",
    "Plated Maul": "weapon2h",
    "Platinum Kris": "weapon1h",
    "Platinum Sceptre": "weapon1h",
    "Poignard": "weapon1h",
    "Poleaxe": "weapon2h",
    "Polished Spiked Shield": "shield",
    "Praetor Crown": "head",
    "Prehistoric Claw": "weapon1h",
    "Primeval Rapier": "weapon1h",
    "Primitive Staff": "weapon2h",
    "Primordial Staff": "weapon2h",
    "Prismatic Ring": "ring",
    "Prophecy Wand": "weapon1h",
    "Prophet Crown": "head",
    "Quarterstaff": "weapon2h",
    "Quartz Sceptre": "weapon1h",
    "Quartz Wand": "weapon1h",
    "Quilted Jacket": "chest",
    "Ranger Bow": "weapon2h",
    "Raven Mask": "head",
    "Rawhide Boots": "feet",
    "Rawhide Gloves": "hands",
    "Rawhide Tower Shield": "shield",
    "Reaver Axe": "weapon1h",
    "Reaver Helmet": "head",
    "Reaver Sword": "weapon2h",
    "Recurve Bow": "weapon2h",
    "Redwood Spiked Shield": "shield",
    "Reef Map": "map",
    "Regicide Mask": "head",
    "Reinforced Greaves": "feet",
    "Reinforced Kite Shield": "shield",
    "Reinforced Tower Shield": "shield",
    "Ringmail Boots": "feet",
    "Ringmail Coat": "chest",
    "Ringmail Gloves": "hands",
    "Ritual Sceptre": "weapon1h",
    "Riveted Boots": "feet",
    "Riveted Gloves": "hands",
    "Rock Breaker": "weapon1h",
    "Rotted Round Shield": "shield",
    "Royal Axe": "weapon1h",
    "Royal Bow": "weapon2h",
    "Royal Burgonet": "head",
    "Royal Sceptre": "weapon1h",
    "Royal Skean": "weapon1h",
    "Royal Staff": "weapon2h",
    "Ruby Ring": "ring",
    "Rugged Quiver": "quiver",
    "Rusted Coif": "head",
    "Rusted Hatchet": "weapon1h",
    "Rusted Spike": "weapon1h",
    "Rusted Sword": "weapon1h",
    "Rustic Sash": "belt",
    "Sabre": "weapon1h",
    "Sadist Garb": "chest",
    "Sage Wand": "weapon1h",
    "Sage's Robe": "chest",
    "Saint's Hauberk": "chest",
    "Saintly Chainmail": "chest",
    "Sallet": "head",
    "Samite Gloves": "hands",
    "Samite Slippers": "feet",
    "Samnite Helmet": "head",
    "Sapphire Ring": "ring",
    "Satin Gloves": "hands",
    "Satin Slippers": "feet",
    "Savant's Robe": "chest",
    "Scale Doublet": "chest",
    "Scale Vest": "chest",
    "Scare Mask": "head",
    "Scarlet Raiment": "chest",
    "Scarlet Round Shield": "shield",
    "Scholar Boots": "feet",
    "Scholar's Robe": "chest",
    "Secutor Helm": "head",
    "Sekhem": "weapon1h",
    "Sentinel Jacket": "chest",
    "Serpent Wand": "weapon1h",
    "Serpentine Staff": "weapon2h",
    "Serpentscale Boots": "feet",
    "Serpentscale Gauntlets": "hands",
    "Serrated Foil": "weapon1h",
    "Sewer Map": "map",
    "Shabby Jerkin": "chest",
    "Shackled Boots": "feet",
    "Shadow Axe": "weapon2h",
    "Shadow Sceptre": "weapon1h",
    "Shagreen Boots": "feet",
    "Shagreen Gloves": "hands",
    "Shagreen Tower Shield": "shield",
    "Sharkskin Boots": "feet",
    "Sharkskin Gloves": "hands",
    "Sharkskin Tunic": "chest",
    "Sharktooth Claw": "weapon1h",
    "Shore Map": "map",
    "Short Bow": "weapon2h",
    "Siege Axe": "weapon1h",
    "Siege Helmet": "head",
    "Silk Gloves": "hands",
    "Silk Robe": "chest",
    "Silk Slippers": "feet",
    "Silken Garb": "chest",
    "Silken Hood": "head",
    "Silken Vest": "chest",
    "Silken Wrap": "chest",
    "Simple Robe": "chest",
    "Sinner Tricorne": "head",
    "Skean": "weapon1h",
    "Skinning Knife": "weapon1h",
    "Slaughter Knife": "weapon1h",
    "Sledgehammer": "weapon2h",
    "Sleek Coat": "chest",
    "Slink Boots": "feet",
    "Slink Gloves": "hands",
    "Sniper Bow": "weapon2h",
    "Solaris Circlet": "head",
    "Soldier Boots": "feet",
    "Soldier Gloves": "hands",
    "Soldier Helmet": "head",
    "Soldier's Brigandine": "chest",
    "Sorcerer Boots": "feet",
    "Sorcerer Gloves": "hands",
    "Sovereign Spiked Shield": "shield",
    "Sparkling Claw": "weapon1h",
    "Spectral Axe": "weapon1h",
    "Spectral Sword": "weapon2h",
    "Spider Forest Map": "map",
    "Spider Lair Map": "map",
    "Spidersilk Robe": "chest",
    "Spiked Bundle": "shield",
    "Spiked Club": "weapon1h",
    "Spiked Maul": "weapon2h",
    "Spiked Round Shield": "shield",
    "Spine Bow": "weapon2h",
    "Spiny Maul": "weapon2h",
    "Spiny Round Shield": "shield",
    "Spiraled Foil": "weapon1h",
    "Spiraled Wand": "weapon1h",
    "Splendid Round Shield": "shield",
    "Splintered Tower Shield": "shield",
    "Springs Map": "map",
    "Stealth Boots": "feet",
    "Stealth Gloves": "hands",
    "Steel Circlet": "head",
    "Steel Gauntlets": "hands",
    "Steel Greaves": "feet",
    "Steel Kite Shield": "shield",
    "Steelhead": "weapon2h",
    "Steelscale Boots": "feet",
    "Steelscale Gauntlets": "hands",
    "Stiletto": "weapon1h",
    "Stone Axe": "weapon2h",
    "Stone Hammer": "weapon1h",
    "Strand Map": "map",
    "Strapped Boots": "feet",
    "Strapped Leather": "chest",
    "Strapped Mitts": "hands",
    "Studded Belt": "belt",
    "Studded Round Shield": "shield",
    "Subterranean Stream Map": "map",
    "Sun Leather": "chest",
    "Sun Plate": "chest",
    "Sundering Axe": "weapon2h",
    "Supreme Spiked Shield": "shield",
    "Tarnished Spirit Shield": "shield",
    "Teak Round Shield": "shield",
    "Tempered Foil": "weapon1h",
    "Tenderizer": "weapon1h",
    "Terror Claw": "weapon1h",
    "Terror Maul": "weapon2h",
    "Thicket Bow": "weapon2h",
    "Thicket Map": "map",
    "Thief's Garb": "chest",
    "Thorium Spirit Shield": "shield",
    "Thorn Rapier": "weapon1h",
    "Thresher Claw": "weapon1h",
    "Throat Stabber": "weapon1h",
    "Tiger Sword": "weapon2h",
    "Tiger's Paw": "weapon1h",
    "Timber Axe": "weapon2h",
    "Timeworn Claw": "weapon1h",
    "Titan Gauntlets": "hands",
    "Titan Greaves": "feet",
    "Titanium Spirit Shield": "shield",
    "Tomahawk": "weapon1h",
    "Tomb Map": "map",
    "Topaz Ring": "ring",
    "Tornado Wand": "weapon1h",
    "Torture Cage": "head",
    "Torture Chamber Map": "map",
    "Totemic Maul": "weapon2h",
    "Trapper Boots": "feet",
    "Trapper Mitts": "hands",
    "Tribal Circlet": "head",
    "Tribal Club": "weapon1h",
    "Tribal Maul": "weapon2h",
    "Tricorne": "head",
    "Triumphant Lamellar": "chest",
    "Tropical Island Map": "map",
    "Tunnel Map": "map",
    "Turquoise Amulet": "amulet",
    "Twig Spirit Shield": "shield",
    "Twilight Blade": "weapon1h",
    "Two-Handed Sword": "weapon2h",
    "Tyrant's Sekhem": "weapon1h",
    "Underground River Map": "map",
    "Underground Sea Map": "map",
    "Ursine Pelt": "head",
    "Vaal Axe": "weapon2h",
    "Vaal Blade": "weapon1h",
    "Vaal Buckler": "shield",
    "Vaal Claw": "weapon1h",
    "Vaal Gauntlets": "hands",
    "Vaal Greatsword": "weapon2h",
    "Vaal Greaves": "feet",
    "Vaal Hatchet": "weapon1h",
    "Vaal Mask": "head",
    "Vaal Pyramid Map": "map",
    "Vaal Rapier": "weapon1h",
    "Vaal Regalia": "chest",
    "Vaal Sceptre": "weapon1h",
    "Vaal Spirit Shield": "shield",
    "Variscite Blade": "weapon1h",
    "Varnished Coat": "chest",
    "Vaults of Atziri Map": "map",
    "Velvet Gloves": "hands",
    "Velvet Slippers": "feet",
    "Vile Staff": "weapon2h",
    "Vine Circlet": "head",
    "Visored Sallet": "head",
    "Void Axe": "weapon2h",
    "Void Sceptre": "weapon1h",
    "Walnut Spirit Shield": "shield",
    "War Axe": "weapon1h",
    "War Buckler": "shield",
    "War Hammer": "weapon1h",
    "War Plate": "chest",
    "War Sword": "weapon1h",
    "Waste Pool Map": "map",
    "Waxed Garb": "chest",
    "Whalebone Rapier": "weapon1h",
    "Widowsilk Robe": "chest",
    "Wild Leather": "chest",
    "Wolf Pelt": "head",
    "Woodful Staff": "weapon2h",
    "Woodsplitter": "weapon2h",
    "Wool Gloves": "hands",
    "Wool Shoes": "feet",
    "Wraith Axe": "weapon1h",
    "Wraith Sword": "weapon2h",
    "Wrapped Boots": "feet",
    "Wrapped Mitts": "hands",
    "Wrist Chopper": "weapon1h",
    "Wyrmbone Rapier": "weapon1h",
    "Wyrmscale Boots": "feet",
    "Wyrmscale Doublet": "chest",
    "Wyrmscale Gauntlets": "hands",
    "Yew Spirit Shield": "shield",
    "Zealot Boots": "feet",
    "Zealot Gloves": "hands",
    "Zealot Helmet": "head",
    "Zodiac Leather": "chest"
}